(async () => {
    const projectKey = 'SpringApi';
    const baseUrl = window.location.origin;
    
    // The list of files you provided earlier
    const files = [
        "src/main/java/com/example/SpringApi/Services/ShippingService.java",
        "src/main/java/com/example/SpringApi/Models/ShippingResponseModel/ShippingOptionsResponseModel.java",
        "src/main/java/com/example/SpringApi/Services/PaymentService.java",
        "src/main/java/com/example/SpringApi/Services/QAService.java",
        "src/main/java/com/example/SpringApi/Services/PurchaseOrderService.java",
        "src/main/java/com/example/SpringApi/Services/PickupLocationService.java",
        "src/main/java/com/example/SpringApi/Models/ShippingResponseModel/GetAllPickupLocationsResponseModel.java",
        "src/main/java/com/example/SpringApi/Models/ResponseModels/ShippingCalculationResponseModel.java",
        "src/main/java/com/example/SpringApi/Helpers/ShipRocketHelper.java",
        "src/main/java/com/example/SpringApi/Services/ProductService.java",
        "src/main/java/com/example/SpringApi/Services/PackageService.java",
        "src/main/java/com/example/SpringApi/FilterQueryBuilder/BaseFilterQueryBuilder.java",
        "src/main/java/com/example/SpringApi/Models/DatabaseModels/Shipment.java",
        "src/main/java/com/example/SpringApi/Services/UserService.java",
        "src/main/java/com/example/SpringApi/Services/LeadService.java",
        "src/main/java/com/example/SpringApi/Services/LoginService.java",
        "src/main/java/com/example/SpringApi/Services/MessageService.java",
        "src/main/java/com/example/SpringApi/Models/DatabaseModels/OrderSummary.java",
        "src/main/java/com/example/SpringApi/Services/UserGroupService.java",
        "src/main/java/com/example/SpringApi/Models/DatabaseModels/Product.java",
        "src/main/java/com/example/SpringApi/Models/ShippingResponseModel/ShipRocketOrderResponseModel.java",
        "src/main/java/com/example/SpringApi/Models/ShippingResponseModel/AddPickupLocationResponseModel.java",
        "src/main/java/com/example/SpringApi/Models/ApiRoutes.java",
        "src/main/java/com/example/SpringApi/Services/PromoService.java",
        "src/main/java/com/example/SpringApi/Services/ClientService.java",
        "src/main/java/com/example/SpringApi/Authentication/JwtTokenProvider.java",
        "src/main/java/com/example/SpringApi/Models/DatabaseModels/Promo.java",
        "src/main/java/com/example/SpringApi/Models/DatabaseModels/Client.java",
        "src/main/java/com/example/SpringApi/Services/TodoService.java",
        "src/main/java/com/example/SpringApi/Services/AddressService.java",
        "src/main/java/com/example/SpringApi/Models/DatabaseModels/Package.java",
        "src/main/java/com/example/SpringApi/Helpers/PasswordHelper.java",
        "src/main/java/com/example/SpringApi/Models/DatabaseModels/Message.java",
        "src/main/java/com/example/SpringApi/Services/ProductReviewService.java",
        "src/main/java/com/example/SpringApi/Services/UserLogService.java",
        "src/main/java/com/example/SpringApi/Models/DatabaseModels/PurchaseOrder.java",
        "src/main/java/com/example/SpringApi/Models/DatabaseModels/User.java",
        "src/main/java/com/example/SpringApi/Models/ResponseModels/UserResponseModel.java",
        "src/main/java/com/example/SpringApi/Models/DatabaseModels/PickupLocation.java",
        "src/main/java/com/example/SpringApi/Authentication/JwtAuthenticationFilter.java",
        "src/main/java/com/example/SpringApi/Models/DatabaseModels/ShipmentPackage.java",
        "src/main/java/com/example/SpringApi/Models/DatabaseModels/ShipmentProduct.java",
        "src/main/java/com/example/SpringApi/Controllers/UserGroupController.java",
        "src/main/java/com/example/SpringApi/Models/RequestModels/PaginationBaseRequestModel.java",
        "src/main/java/com/example/SpringApi/Models/DatabaseModels/ProductPickupLocationMapping.java",
        "src/main/java/com/example/SpringApi/Models/DatabaseModels/Todo.java",
        "src/main/java/com/example/SpringApi/Exceptions/ApplicationException.java",
        "src/main/java/com/example/SpringApi/Helpers/BrevoEmailHelper.java",
        "src/main/java/com/example/SpringApi/Models/DatabaseModels/ProductCategory.java",
        "src/main/java/com/example/SpringApi/Models/DatabaseModels/ShipmentPackageProduct.java",
        "src/main/java/com/example/SpringApi/Models/DatabaseModels/Address.java",
        "src/main/java/com/example/SpringApi/Models/DatabaseModels/Lead.java",
        "src/main/java/com/example/SpringApi/Models/DatabaseModels/UserGroupUserMap.java",
        "src/main/java/com/example/SpringApi/Authentication/Authorization.java",
        "src/main/java/com/example/SpringApi/Services/BaseService.java",
        "src/main/java/com/example/SpringApi/Models/DatabaseModels/ProductReview.java",
        "src/main/java/com/example/SpringApi/Models/DatabaseModels/UserGroup.java",
        "src/main/java/com/example/SpringApi/Controllers/PaymentController.java",
        "src/main/java/com/example/SpringApi/Controllers/PurchaseOrderController.java",
        "src/main/java/com/example/SpringApi/Controllers/UserLogController.java",
        "src/main/java/com/example/SpringApi/Controllers/AddressController.java",
        "src/main/java/com/example/SpringApi/Repositories/AddressRepository.java",
        "src/main/java/com/example/SpringApi/Models/RequestModels/AddressRequestModel.java",
        "src/main/java/com/example/SpringApi/Models/ResponseModels/AddressResponseModel.java",
        "src/main/java/com/example/SpringApi/Models/Authorizations.java",
        "src/main/java/com/example/SpringApi/Exceptions/BadRequestException.java",
        "src/main/java/com/example/SpringApi/Helpers/BulkInsertHelper.java",
        "src/main/java/com/example/SpringApi/Models/ResponseModels/BulkInsertResponseModel.java",
        "src/main/java/com/example/SpringApi/Models/ResponseModels/BulkUserInsertResponseModel.java",
        "src/main/java/com/example/SpringApi/Models/RequestModels/CashPaymentRequestModel.java",
        "src/main/java/com/example/SpringApi/Controllers/ClientController.java",
        "src/main/java/com/example/SpringApi/Repositories/ClientRepository.java",
        "src/main/java/com/example/SpringApi/Models/RequestModels/ClientRequestModel.java",
        "src/main/java/com/example/SpringApi/Models/ResponseModels/ClientResponseModel.java",
        "src/main/java/com/example/SpringApi/Exceptions/ConflictException.java",
        "src/main/java/com/example/SpringApi/Logging/ContextualLogger.java",
        "src/main/java/com/example/SpringApi/Config/CorsConfig.java",
        "src/main/java/com/example/SpringApi/Models/RequestModels/CreateReturnRequestModel.java",
        "src/main/java/com/example/SpringApi/Authentication/CustomUserDetailsService.java",
        "src/main/java/com/example/SpringApi/DataSource/DatabaseConfig.java",
        "src/main/java/com/example/SpringApi/Adapters/DateAdapter.java",
        "src/main/java/com/example/SpringApi/Helpers/EmailHelper.java",
        "src/main/java/com/example/SpringApi/Helpers/EmailHelperFactory.java",
        "src/main/java/com/example/SpringApi/Helpers/EmailTemplates.java",
        "src/main/java/com/example/SpringApi/Constants/EntityType.java",
        "src/main/java/com/example/SpringApi/ErrorMessages.java",
        "src/main/java/com/example/SpringApi/Models/ResponseModels/ErrorResponseModel.java",
        "src/main/java/com/example/SpringApi/Helpers/FirebaseHelper.java",
        "src/main/java/com/example/SpringApi/Deserializers/FlexibleLocalDateTimeDeserializer.java",
        "src/main/java/com/example/SpringApi/Exceptions/GlobalExceptionHandler.java",
        "src/main/java/com/example/SpringApi/Models/DatabaseModels/GoogleCred.java",
        "src/main/java/com/example/SpringApi/Repositories/GoogleCredRepository.java",
        "src/main/java/com/example/SpringApi/Helpers/HTMLHelper.java",
        "src/main/java/com/example/SpringApi/Services/Interface/IAddressSubTranslator.java",
        "src/main/java/com/example/SpringApi/Services/Interface/IClientSubTranslator.java",
        "src/main/java/com/example/SpringApi/Helpers/IEmailHelper.java",
        "src/main/java/com/example/SpringApi/Services/Interface/ILeadSubTranslator.java",
        "src/main/java/com/example/SpringApi/Services/Interface/ILoginSubTranslator.java",
        "src/main/java/com/example/SpringApi/Constants/ImageLocationConstants.java",
        "src/main/java/com/example/SpringApi/Services/Interface/IMessageSubTranslator.java",
        "src/main/java/com/example/SpringApi/Helpers/ImgbbHelper.java",
        "src/main/java/com/example/SpringApi/Services/Interface/IPackageSubTranslator.java",
        "src/main/java/com/example/SpringApi/Services/Interface/IPaymentSubTranslator.java",
        "src/main/java/com/example/SpringApi/Services/Interface/IPickupLocationSubTranslator.java",
        "src/main/java/com/example/SpringApi/Services/Interface/IProductReviewSubTranslator.java",
        "src/main/java/com/example/SpringApi/Services/Interface/IProductSubTranslator.java",
        "src/main/java/com/example/SpringApi/Services/Interface/IPromoSubTranslator.java",
        "src/main/java/com/example/SpringApi/Services/Interface/IPurchaseOrderSubTranslator.java",
        "src/main/java/com/example/SpringApi/Services/Interface/IQASubTranslator.java",
        "src/main/java/com/example/SpringApi/Services/Interface/IShipmentSubTranslator.java",
        "src/main/java/com/example/SpringApi/Services/Interface/IShippingSubTranslator.java",
        "src/main/java/com/example/SpringApi/Services/Interface/ITodoSubTranslator.java",
        "src/main/java/com/example/SpringApi/Services/Interface/IUserGroupSubTranslator.java",
        "src/main/java/com/example/SpringApi/Services/Interface/IUserLogSubTranslator.java",
        "src/main/java/com/example/SpringApi/Services/Interface/IUserSubTranslator.java",
        "src/main/java/com/example/SpringApi/Models/DatabaseModels/LatestTestResult.java",
        "src/main/java/com/example/SpringApi/Repositories/LatestTestResultRepository.java",
        "src/main/java/com/example/SpringApi/Models/ResponseModels/LatestTestResultResponseModel.java",
        "src/main/java/com/example/SpringApi/Controllers/LeadController.java",
        "src/main/java/com/example/SpringApi/FilterQueryBuilder/LeadFilterQueryBuilder.java",
        "src/main/java/com/example/SpringApi/Repositories/LeadRepository.java",
        "src/main/java/com/example/SpringApi/Models/RequestModels/LeadRequestModel.java",
        "src/main/java/com/example/SpringApi/Models/ResponseModels/LeadResponseModel.java",
        "src/main/java/com/example/SpringApi/Adapters/LocalDateTimeAdapter.java",
        "src/main/java/com/example/SpringApi/Controllers/LoginController.java",
        "src/main/java/com/example/SpringApi/Models/RequestModels/LoginRequestModel.java",
        "src/main/java/com/example/SpringApi/Controllers/MessageController.java",
        "src/main/java/com/example/SpringApi/Repositories/MessageRepository.java",
        "src/main/java/com/example/SpringApi/Models/RequestModels/MessageRequestModel.java",
        "src/main/java/com/example/SpringApi/Models/ResponseModels/MessageResponseModel.java",
        "src/main/java/com/example/SpringApi/Models/DatabaseModels/MessageUserGroupMap.java",
        "src/main/java/com/example/SpringApi/Repositories/MessageUserGroupMapRepository.java",
        "src/main/java/com/example/SpringApi/Models/DatabaseModels/MessageUserMap.java",
        "src/main/java/com/example/SpringApi/Repositories/MessageUserMapRepository.java",
        "src/main/java/com/example/SpringApi/Models/DatabaseModels/MessageUserReadMap.java",
        "src/main/java/com/example/SpringApi/Repositories/MessageUserReadMapRepository.java",
        "src/main/java/com/example/SpringApi/Models/DTOs/MessageWithTargetsDTO.java",
        "src/main/java/com/example/SpringApi/Exceptions/NotFoundException.java",
        "src/main/java/com/example/SpringApi/Models/RequestModels/OrderOptimizationRequestModel.java",
        "src/main/java/com/example/SpringApi/Models/ResponseModels/OrderOptimizationResponseModel.java",
        "src/main/java/com/example/SpringApi/Repositories/OrderSummaryRepository.java",
        "src/main/java/com/example/SpringApi/Models/ResponseModels/OrderSummaryResponseModel.java",
        "src/main/java/com/example/SpringApi/Controllers/PackageController.java",
        "src/main/java/com/example/SpringApi/FilterQueryBuilder/PackageFilterQueryBuilder.java",
        "src/main/java/com/example/SpringApi/Models/DatabaseModels/PackagePickupLocationMapping.java",
        "src/main/java/com/example/SpringApi/Repositories/PackagePickupLocationMappingRepository.java",
        "src/main/java/com/example/SpringApi/Models/RequestModels/PackagePickupLocationMappingRequestModel.java",
        "src/main/java/com/example/SpringApi/Models/ResponseModels/PackagePickupLocationMappingResponseModel.java",
        "src/main/java/com/example/SpringApi/Repositories/PackageRepository.java",
        "src/main/java/com/example/SpringApi/Models/RequestModels/PackageRequestModel.java",
        "src/main/java/com/example/SpringApi/Models/ResponseModels/PackageResponseModel.java",
        "src/main/java/com/example/SpringApi/Helpers/PackagingHelper.java",
        "src/main/java/com/example/SpringApi/Models/ResponseModels/PaginationBaseResponseModel.java",
        "src/main/java/com/example/SpringApi/Models/DatabaseModels/Payment.java",
        "src/main/java/com/example/SpringApi/Repositories/PaymentRepository.java",
        "src/main/java/com/example/SpringApi/Models/ResponseModels/PaymentResponseModel.java",
        "src/main/java/com/example/SpringApi/Models/ResponseModels/PaymentVerificationResponseModel.java",
        "src/main/java/com/example/SpringApi/Helpers/PDFHelper.java",
        "src/main/java/com/example/SpringApi/Models/DatabaseModels/Permission.java",
        "src/main/java/com/example/SpringApi/Exceptions/PermissionException.java",
        "src/main/java/com/example/SpringApi/Repositories/PermissionRepository.java",
        "src/main/java/com/example/SpringApi/Models/ResponseModels/PermissionResponseModel.java",
        "src/main/java/com/example/SpringApi/Controllers/PickupLocationController.java",
        "src/main/java/com/example/SpringApi/FilterQueryBuilder/PickupLocationFilterQueryBuilder.java",
        "src/main/java/com/example/SpringApi/Repositories/PickupLocationRepository.java",
        "src/main/java/com/example/SpringApi/Models/RequestModels/PickupLocationRequestModel.java",
        "src/main/java/com/example/SpringApi/Models/ResponseModels/PickupLocationResponseModel.java",
        "pom.xml",
        "src/main/java/com/example/SpringApi/Models/RequestModels/ProcessPaymentAndShipmentRequestModel.java",
        "src/main/java/com/example/SpringApi/Repositories/ProductCategoryRepository.java",
        "src/main/java/com/example/SpringApi/Models/RequestModels/ProductCategoryRequestModel.java",
        "src/main/java/com/example/SpringApi/Models/ResponseModels/ProductCategoryResponseModel.java",
        "src/main/java/com/example/SpringApi/Models/ResponseModels/ProductCategoryWithPathResponseModel.java",
        "src/main/java/com/example/SpringApi/Constants/ProductConditionConstants.java",
        "src/main/java/com/example/SpringApi/Controllers/ProductController.java",
        "src/main/java/com/example/SpringApi/FilterQueryBuilder/ProductFilterQueryBuilder.java",
        "src/main/java/com/example/SpringApi/Constants/ProductImageConstants.java",
        "src/main/java/com/example/SpringApi/Models/ResponseModels/ProductPickupLocationItem.java",
        "src/main/java/com/example/SpringApi/Repositories/ProductPickupLocationMappingRepository.java",
        "src/main/java/com/example/SpringApi/Models/RequestModels/ProductPickupLocationMappingRequestModel.java",
        "src/main/java/com/example/SpringApi/Repositories/ProductRepository.java",
        "src/main/java/com/example/SpringApi/Models/RequestModels/ProductRequestModel.java",
        "src/main/java/com/example/SpringApi/Models/ResponseModels/ProductResponseModel.java",
        "src/main/java/com/example/SpringApi/Controllers/ProductReviewController.java",
        "src/main/java/com/example/SpringApi/FilterQueryBuilder/ProductReviewFilterQueryBuilder.java",
        "src/main/java/com/example/SpringApi/Repositories/ProductReviewRepository.java",
        "src/main/java/com/example/SpringApi/Models/RequestModels/ProductReviewRequestModel.java",
        "src/main/java/com/example/SpringApi/Models/ResponseModels/ProductReviewResponseModel.java",
        "src/main/java/com/example/SpringApi/Models/ResponseModels/ProductStockByLocationResponseModel.java",
        "src/main/java/com/example/SpringApi/Controllers/PromoController.java",
        "src/main/java/com/example/SpringApi/FilterQueryBuilder/PromoFilterQueryBuilder.java",
        "src/main/java/com/example/SpringApi/Repositories/PromoRepository.java",
        "src/main/java/com/example/SpringApi/Models/RequestModels/PromoRequestModel.java",
        "src/main/java/com/example/SpringApi/Models/ResponseModels/PromoResponseModel.java",
        "src/main/java/com/example/SpringApi/FilterQueryBuilder/PurchaseOrderFilterQueryBuilder.java",
        "src/main/java/com/example/SpringApi/Models/RequestModels/PurchaseOrderProductItem.java",
        "src/main/java/com/example/SpringApi/Models/ResponseModels/PurchaseOrderProductItem.java",
        "src/main/java/com/example/SpringApi/Repositories/PurchaseOrderRepository.java",
        "src/main/java/com/example/SpringApi/Models/RequestModels/PurchaseOrderRequestModel.java",
        "src/main/java/com/example/SpringApi/Models/ResponseModels/PurchaseOrderResponseModel.java",
        "src/main/java/com/example/SpringApi/Models/DTOs/PurchaseOrderWithDetails.java",
        "src/main/java/com/example/SpringApi/Controllers/QAController.java",
        "src/main/java/com/example/SpringApi/Models/ResponseModels/QADashboardResponseModel.java",
        "src/main/java/com/example/SpringApi/Models/ResponseModels/QAResponseModel.java",
        "src/main/java/com/example/SpringApi/Models/RequestModels/RazorpayOrderRequestModel.java",
        "src/main/java/com/example/SpringApi/Models/ResponseModels/RazorpayOrderResponseModel.java",
        "src/main/java/com/example/SpringApi/Models/RequestModels/RazorpayVerifyRequestModel.java",
        "src/main/java/com/example/SpringApi/RequestContext.java",
        "src/main/java/com/example/SpringApi/Models/ResponseModels/ResourceResponseModel.java",
        "src/main/java/com/example/SpringApi/Models/DatabaseModels/Resources.java",
        "src/main/java/com/example/SpringApi/Repositories/ResourcesRepository.java",
        "src/main/java/com/example/SpringApi/Models/DatabaseModels/ReturnShipment.java",
        "src/main/java/com/example/SpringApi/Models/DatabaseModels/ReturnShipmentProduct.java",
        "src/main/java/com/example/SpringApi/Repositories/ReturnShipmentProductRepository.java",
        "src/main/java/com/example/SpringApi/Repositories/ReturnShipmentRepository.java",
        "src/main/java/com/example/SpringApi/Models/ResponseModels/ReturnShipmentResponseModel.java",
        "src/main/java/com/example/SpringApi/Authentication/SecurityConfig.java",
        "src/main/java/com/example/SpringApi/Models/RequestModels/SendEmailRequest.java",
        "src/main/java/com/example/SpringApi/Controllers/ShipmentController.java",
        "src/main/java/com/example/SpringApi/FilterQueryBuilder/ShipmentFilterQueryBuilder.java",
        "src/main/java/com/example/SpringApi/Repositories/ShipmentPackageProductRepository.java",
        "src/main/java/com/example/SpringApi/Repositories/ShipmentPackageRepository.java",
        "src/main/java/com/example/SpringApi/Repositories/ShipmentProductRepository.java",
        "src/main/java/com/example/SpringApi/Repositories/ShipmentRepository.java",
        "src/main/java/com/example/SpringApi/Models/ResponseModels/ShipmentResponseModel.java",
        "src/main/java/com/example/SpringApi/Models/RequestModels/ShippingCalculationRequestModel.java",
        "src/main/java/com/example/SpringApi/Controllers/ShippingController.java",
        "src/main/java/com/example/SpringApi/Models/ShippingResponseModel/ShipRocketAwbResponseModel.java",
        "src/main/java/com/example/SpringApi/Models/ShippingResponseModel/ShipRocketInvoiceResponseModel.java",
        "src/main/java/com/example/SpringApi/Models/ShippingResponseModel/ShipRocketLabelResponseModel.java",
        "src/main/java/com/example/SpringApi/Models/ShippingResponseModel/ShipRocketManifestResponseModel.java",
        "src/main/java/com/example/SpringApi/Models/ShippingResponseModel/ShipRocketOrderDetailsResponseModel.java",
        "src/main/java/com/example/SpringApi/Models/RequestModels/ShipRocketOrderRequestModel.java",
        "src/main/java/com/example/SpringApi/Models/ShippingResponseModel/ShipRocketPickupResponseModel.java",
        "src/main/java/com/example/SpringApi/Models/RequestModels/ShipRocketReturnOrderRequestModel.java",
        "src/main/java/com/example/SpringApi/Models/ShippingResponseModel/ShipRocketReturnOrderResponseModel.java",
        "src/main/java/com/example/SpringApi/Models/ShippingResponseModel/ShipRocketTrackingResponseModel.java",
        "src/main/java/com/example/SpringApi/SpringApiApplication.java",
        "src/main/java/com/example/SpringApi/SuccessMessages.java",
        "src/main/java/com/example/SpringApi/Models/RequestModels/TestExecutionRequestModel.java",
        "src/main/java/com/example/SpringApi/Models/ResponseModels/TestExecutionStatusModel.java",
        "src/main/java/com/example/SpringApi/Models/DatabaseModels/TestRun.java",
        "src/main/java/com/example/SpringApi/Repositories/TestRunRepository.java",
        "src/main/java/com/example/SpringApi/Models/RequestModels/TestRunRequestModel.java",
        "src/main/java/com/example/SpringApi/Models/ResponseModels/TestRunResponseModel.java",
        "src/main/java/com/example/SpringApi/Models/DatabaseModels/TestRunResult.java",
        "src/main/java/com/example/SpringApi/Repositories/TestRunResultRepository.java",
        "src/main/java/com/example/SpringApi/Controllers/TodoController.java",
        "src/main/java/com/example/SpringApi/Repositories/TodoRepository.java",
        "src/main/java/com/example/SpringApi/Models/RequestModels/TodoRequestModel.java",
        "src/main/java/com/example/SpringApi/Models/ResponseModels/TodoResponseModel.java",
        "src/main/java/com/example/SpringApi/Models/ShippingResponseModel/TokenResponseModel.java",
        "src/main/java/com/example/SpringApi/Exceptions/UnauthorizedException.java",
        "src/main/java/com/example/SpringApi/Models/ShippingResponseModel/UpdatePickupLocationResponseModel.java",
        "src/main/java/com/example/SpringApi/Models/DatabaseModels/UserClientMapping.java",
        "src/main/java/com/example/SpringApi/Repositories/UserClientMappingRepository.java",
        "src/main/java/com/example/SpringApi/Models/DatabaseModels/UserClientPermissionMapping.java",
        "src/main/java/com/example/SpringApi/Repositories/UserClientPermissionMappingRepository.java",
        "src/main/java/com/example/SpringApi/Controllers/UserController.java",
        "src/main/java/com/example/SpringApi/FilterQueryBuilder/UserFilterQueryBuilder.java",
        "src/main/java/com/example/SpringApi/Models/DatabaseModels/UserGridPreference.java",
        "src/main/java/com/example/SpringApi/Repositories/UserGridPreferenceRepository.java",
        "src/main/java/com/example/SpringApi/FilterQueryBuilder/UserGroupFilterQueryBuilder.java",
        "src/main/java/com/example/SpringApi/Repositories/UserGroupRepository.java",
        "src/main/java/com/example/SpringApi/Models/RequestModels/UserGroupRequestModel.java",
        "src/main/java/com/example/SpringApi/Models/ResponseModels/UserGroupResponseModel.java",
        "src/main/java/com/example/SpringApi/Repositories/UserGroupUserMapRepository.java",
        "src/main/java/com/example/SpringApi/Models/DatabaseModels/UserLog.java",
        "src/main/java/com/example/SpringApi/FilterQueryBuilder/UserLogFilterQueryBuilder.java",
        "src/main/java/com/example/SpringApi/Repositories/UserLogRepository.java",
        "src/main/java/com/example/SpringApi/Models/RequestModels/UserLogsRequestModel.java",
        "src/main/java/com/example/SpringApi/Models/ResponseModels/UserLogsResponseModel.java",
        "src/main/java/com/example/SpringApi/Repositories/UserRepository.java",
        "src/main/java/com/example/SpringApi/Models/RequestModels/UserRequestModel.java",
        "src/main/java/com/example/SpringApi/Constants/UserRole.java"
    ];

    let report = [];

    console.log(`Starting extraction for ${files.length} files...`);

    for (let i = 0; i < files.length; i++) {
        const filePath = files[i];
        const componentKey = `${projectKey}:${filePath}`;
        const url = `${baseUrl}/api/sources/lines?key=${encodeURIComponent(componentKey)}&fields=coverage`;

        try {
            console.log(`[${i + 1}/${files.length}] Fetching: ${filePath}`);
            const response = await fetch(url);
            
            if (!response.ok) {
                console.error(`Failed to fetch ${filePath}: ${response.status}`);
                continue;
            }

            const data = await response.json();
            
            if (data.sources) {
                const uncoveredLines = data.sources
                    .filter(l => l.utStatus === 'uncovered' || l.lineHits === 0 || l.utLineHits === 0)
                    .map(l => l.line);

                if (uncoveredLines.length > 0) {
                    report.push({
                        file: filePath,
                        uncovered_count: uncoveredLines.length,
                        line_numbers: uncoveredLines
                    });
                }
            }
        } catch (err) {
            console.error(`Error processing ${filePath}:`, err);
        }
    }

    console.log("Extraction complete. Preparing download...");

    // Create and trigger the download
    const blob = new Blob([JSON.stringify(report, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'sonar_uncovered_lines.json';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    console.log("Success! Your file 'sonar_uncovered_lines.json' has been downloaded.");
})();